name: my-dev-vault-cluster

services:
  vault-server1:
    image: hashicorp/vault:1.18
    hostname:  vault-dev-server1
    container_name: vault-dev-server1
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    networks:
      - vault-cluster-network
    environment:
      - VAULT_ADDR=http://localhost:8200

  vault-server2:
    image: hashicorp/vault:1.17
    hostname:  vault-dev-server2
    container_name: vault-dev-server2
    ports:
      - "8202:8200"
    cap_add:
      - IPC_LOCK
    networks:
      - vault-cluster-network
    environment:
      - VAULT_ADDR=http://localhost:8200
      

  vault-server3:
    image: hashicorp/vault:1.17
    hostname:  vault-dev-server3
    container_name: vault-dev-server3
    ports:
      - "8204:8200"
    cap_add:
      - IPC_LOCK
    networks:
      - vault-cluster-network
    environment:
      - VAULT_ADDR=http://localhost:8200

networks:
  vault-cluster-network:
    driver: bridge
    